#---------------------
#     ConfigMap
#---------------------

apiVersion: v1
kind: ConfigMap
metadata:
  name: node-tekton-config
  labels:
    app: node-tekton-config
#  namespace: mytest

data:
  NODETEKTON_PORT: "3010"
  TEKTON_VERSION : "1.0"

