#---------------------
#     ConfigMap
#---------------------

apiVersion: v1
kind: ConfigMap
metadata:
  name: node-kafka-config
  namespace: development
  labels:
    app: node-kafka-config
data:
  NODE_KAFKA_PORT: "3090"
  NODE_KAFKA_FILE: "/app/kafka.txt" 
  KAFKA_VERSION: "1.0"

---
#---------------------
#     Deployment
#---------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-kafka
spec:
  selector:
    matchLabels:
      app: node-kafka
  template:
    metadata:
      labels:
        app: node-kafka
    spec:
      containers:
      - name: app
        image: vincent/node-kafka:latest
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name:  node-kafka-config

---
#---------------------
# NodePort 
#---------------------
apiVersion: v1
kind: Service
metadata:
  name: node-kafka-np
  labels:
    app: node-kafka
spec:
  type: NodePort
  ports:
   - port: 3090
     nodePort: 30021
  selector:
   app: node-kafka

---
#---------------------
# ClusterIP
#---------------------

apiVersion: v1
kind: Service
metadata:
  name: node-kafka-clu
  labels:
    app: node-kafka-clu
spec:
  type: ClusterIP
  ports:
   - port: 3090
     protocol: TCP
     targetPort: 3090
  selector:
   app:  node-kafka


