#---------------------
#     ConfigMap
#---------------------

apiVersion: v1
kind: ConfigMap
metadata:
  name: node-slim-config
  namespace: development
  labels:
    app: node-slim-config
data:
  NODESLIM_PORT: "3011"

---
#---------------------
#     Deployment
#---------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-slim
spec:
  selector:
    matchLabels:
      app: node-slim
  template:
    metadata:
      labels:
        app: node-slim
    spec:
      containers:
      - name: app
        image: vincent/node-slim:2.0.0
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name:  node-slim-config

---
#---------------------
# NodePort 
#---------------------
apiVersion: v1
kind: Service
metadata:
  name: node-slim-np
  labels:
    app: node-slim-np
spec:
  type: NodePort
  ports:
   - port: 3011
     nodePort: 30025
  selector:
   app: node-slim

---
#---------------------
# ClusterIP
#---------------------

apiVersion: v1
kind: Service
metadata:
  name: node-slim-clu
  labels:
    app: node-slim-clu
spec:
  type: ClusterIP
  ports:
   - port: 3011
     protocol: TCP
     targetPort: 3011
  selector:
   app:  node-slim


